### PR TITLE
show accounts that liked a post in a dropdown

### LINKED ISSUE #22: feat: Show accounts that liked a post in a dropdown
**Current State:** The Gigs Board does not display who liked a post:
Like-Posts

**Desired State:** Apply the same behavior from NEAR Social (showing users who liked the post + dropdown):
Like-Dropdown

### PR DESCRIPTION
**Pull request by ailisp**
This PR will close #22 

Preview:
image

image

image

### CODE REVIEW

**Comment by frol** [comment]
@ailisp Let's replicate the UI instead of mixing the two:

Desired state:
Like-Dropdown

**Comment by ailisp** [comment]
@frol Does red heart play well with blue "Reply" & "Expand Replies"? I feel my version looks more consistent. @ori-near what is your opinion?

**Comment by frol** [comment]
We may keep the heart blue, but "Like (100)" duplicates the avatars and "and 97 others", and the hover blue background makes it impossible to read the text:

image

**Comment by ailisp** [comment]
Current preview:

A post without likes:

image

A post with 1 like:
image

A post with 3 likes:
image

A post with more than 3 likes:
image

image

**Comment by ori-near** [comment]
Hi @frol and @ailisp – thanks for the discussion above. I think @ailisp's latest solution is a good solution for now. And I think we can revisit the general UI / branding in the near future.

**Review by frol — APPROVED** [review]

**Pull request merged**
